# Generated by Django 6.0.4 on 2026-05-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0051_systemsetting_psa_csat_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, help_text='Plain-text body. Rendered with newlines preserved.')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Critical')], default='info', help_text='Visual treatment — info (blue), success (green), warning (yellow), danger (red).', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive announcements are hidden from the portal regardless of expiry.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, announcement is hidden after this time. Leave blank for no expiry.', null=True)),
                ('is_dismissable', models.BooleanField(default=True, help_text='When true, portal users can hide the banner for themselves (stored per-session). Critical announcements should set this to False.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_announcements_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Client org whose portal users should see this banner.', on_delete=django.db.models.deletion.CASCADE, related_name='portal_announcements', to='core.organization')),
            ],
            options={
                'db_table': 'portal_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active', '-created_at'], name='portal_anno_organiz_a1b106_idx'), models.Index(fields=['expires_at'], name='portal_anno_expires_c6c70b_idx')],
            },
        ),
    ]
