# Generated by Django 6.0.4 on 2026-05-08 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Compliance categories',
                'ordering': ['framework', 'order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('recertification_default_days', models.PositiveIntegerField(default=365)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='What the control requires (verbatim where possible).')),
                ('evidence_hint', models.TextField(blank=True, help_text='What evidence the auditor typically expects.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compliance.compliancecategory')),
            ],
            options={
                'ordering': ['category', 'order', 'slug'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='compliancecategory',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='compliance.complianceframework'),
        ),
        migrations.CreateModel(
            name='OrganizationCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('recertification_interval_days', models.PositiveIntegerField(default=365)),
                ('recertification_emails_enabled', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, help_text="If set, recertification reminders go here. Otherwise the org's primary admin email.", max_length=254)),
                ('last_recertified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_enrollments', to='compliance.complianceframework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_enrollments', to='core.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization compliance enrollments',
                'ordering': ['organization', 'framework'],
                'unique_together': {('organization', 'framework')},
            },
        ),
        migrations.CreateModel(
            name='RecertificationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('message_id', models.CharField(blank=True, max_length=200)),
                ('org_compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='compliance.organizationcompliance')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='compliancecategory',
            unique_together={('framework', 'slug')},
        ),
        migrations.CreateModel(
            name='OrganizationComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unanswered', 'Unanswered'), ('compliant', 'Compliant'), ('partial', 'Partial'), ('non_compliant', 'Non-compliant'), ('not_applicable', 'Not applicable')], default='unanswered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('evidence_link', models.URLField(blank=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_attestations', to='compliance.compliancecheckitem')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_compliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_attestations', to='compliance.organizationcompliance')),
            ],
            options={
                'ordering': ['org_compliance', 'item'],
                'unique_together': {('org_compliance', 'item')},
            },
        ),
    ]
