"""
Integrations app tests.

Currently focused on the Workstream 8 distributor surface (DistributorConnection
+ Ingram Xvantage adapter + webhook signature verification). The PSA/RMM
sync paths are exercised in their own debug commands and via the upstream
provider sandboxes; we don't mock those here.
"""
from __future__ import annotations

import hashlib
import hmac
import json

from django.test import TestCase, override_settings

from core.models import Organization
from .models import DistributorConnection, DistributorWebhookEvent


class DistributorConnectionModelTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')

    def test_credential_round_trip_is_encrypted(self):
        conn = DistributorConnection.objects.create(
            organization=self.org,
            provider_type='ingram_xvantage',
            name='Ingram Sandbox',
        )
        conn.set_credentials({
            'client_id': 'abc123',
            'client_secret': 'shhh',
            'customer_number': 'C0001',
        })
        conn.save()

        reloaded = DistributorConnection.objects.get(pk=conn.pk)
        creds = reloaded.get_credentials()
        self.assertEqual(creds['client_id'], 'abc123')
        self.assertEqual(creds['client_secret'], 'shhh')
        self.assertEqual(creds['customer_number'], 'C0001')
        # Ciphertext must not contain the plaintext secret.
        self.assertNotIn('shhh', reloaded.encrypted_credentials)

    def test_webhook_token_is_autogenerated_and_unique(self):
        c1 = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='A')
        c2 = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='B')
        self.assertTrue(c1.webhook_token)
        self.assertTrue(c2.webhook_token)
        self.assertNotEqual(c1.webhook_token, c2.webhook_token)
        # token_urlsafe(32) → ~43 chars, base64url-safe alphabet
        self.assertGreaterEqual(len(c1.webhook_token), 32)

    def test_webhook_secret_round_trips(self):
        conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage', name='X')
        conn.set_webhook_secret('very-secret-hmac-key')
        conn.save()
        reloaded = DistributorConnection.objects.get(pk=conn.pk)
        self.assertEqual(reloaded.get_webhook_secret(), 'very-secret-hmac-key')
        self.assertNotIn('very-secret', reloaded.encrypted_webhook_secret)


class IngramAdapterTests(TestCase):
    """
    The provider does no live HTTP at construction time, so we can build
    one and exercise its parser/signature logic without mocking out
    requests. Network-touching methods are exercised against the
    Ingram sandbox in manual QA.
    """

    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')
        self.conn = DistributorConnection.objects.create(
            organization=self.org,
            provider_type='ingram_xvantage',
            name='Ingram',
            base_url='',  # exercise the DEFAULT_BASE_URL fallback
        )
        self.conn.set_credentials({'client_id': 'cid', 'client_secret': 'csec',
                                   'customer_number': 'C-1'})
        self.conn.set_webhook_secret('hmac-secret')
        self.conn.save()

    def _provider(self):
        from .providers.distributors import get_distributor_provider
        return get_distributor_provider(self.conn)

    def test_provider_resolution(self):
        p = self._provider()
        self.assertIsNotNone(p)
        self.assertEqual(p.provider_name, 'Ingram Micro Xvantage')

    def test_default_base_url_filled_when_blank(self):
        # Reload the connection — the provider __init__ writes the default
        # back onto connection.base_url before BaseProvider's SSRF check.
        p = self._provider()
        self.assertTrue(p.base_url)
        self.assertIn('ingrammicro.com', p.base_url)

    def test_handle_webhook_valid_signature(self):
        p = self._provider()
        body = json.dumps({'eventType': 'order.shipped', 'order_id': 'X1'}).encode()
        sig = hmac.new(b'hmac-secret', body, hashlib.sha256).hexdigest()
        result = p.handle_webhook(
            headers={'X-Ingram-Signature': f'sha256={sig}'}, raw_body=body
        )
        self.assertTrue(result['signature_valid'])
        self.assertEqual(result['event_type'], 'order.shipped')
        self.assertEqual(result['parsed']['order_id'], 'X1')

    def test_handle_webhook_invalid_signature(self):
        p = self._provider()
        body = b'{"eventType":"order.shipped"}'
        result = p.handle_webhook(
            headers={'X-Ingram-Signature': 'sha256=deadbeef'}, raw_body=body
        )
        self.assertFalse(result['signature_valid'])

    def test_handle_webhook_missing_signature(self):
        p = self._provider()
        result = p.handle_webhook(headers={}, raw_body=b'{}')
        self.assertFalse(result['signature_valid'])

    def test_handle_webhook_malformed_body(self):
        p = self._provider()
        result = p.handle_webhook(headers={}, raw_body=b'not-json')
        self.assertFalse(result['signature_valid'])
        self.assertEqual(result['parsed'], {})


@override_settings(SECURE_SSL_REDIRECT=False)
class DistributorWebhookEndpointTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name='Acme MSP')
        self.conn = DistributorConnection.objects.create(
            organization=self.org, provider_type='ingram_xvantage',
            name='Ingram', is_active=True,
        )
        self.conn.set_webhook_secret('topsecret')
        self.conn.save()

    def test_unknown_token_returns_404(self):
        resp = self.client.post(
            '/integrations/distributors/webhooks/not-a-real-token/',
            data=b'{}', content_type='application/json',
        )
        self.assertEqual(resp.status_code, 404)
        self.assertEqual(DistributorWebhookEvent.objects.count(), 0)

    def test_valid_signature_records_event(self):
        body = json.dumps({'eventType': 'order.delivered'}).encode()
        sig = hmac.new(b'topsecret', body, hashlib.sha256).hexdigest()
        url = f'/integrations/distributors/webhooks/{self.conn.webhook_token}/'
        resp = self.client.post(
            url, data=body, content_type='application/json',
            HTTP_X_INGRAM_SIGNATURE=f'sha256={sig}',
        )
        self.assertEqual(resp.status_code, 200)
        event = DistributorWebhookEvent.objects.get(connection=self.conn)
        self.assertTrue(event.signature_valid)
        self.assertEqual(event.event_type, 'order.delivered')
        self.assertTrue(event.processed)

    def test_invalid_signature_recorded_but_processed_true(self):
        # The webhook endpoint always records — signature_valid false flags it.
        url = f'/integrations/distributors/webhooks/{self.conn.webhook_token}/'
        resp = self.client.post(
            url, data=b'{"eventType":"x"}', content_type='application/json',
            HTTP_X_INGRAM_SIGNATURE='sha256=00',
        )
        self.assertEqual(resp.status_code, 200)
        event = DistributorWebhookEvent.objects.get(connection=self.conn)
        self.assertFalse(event.signature_valid)
