# Generated by Django 6.0.4 on 2026-04-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_python_pack_scan_da_idx_python_pack_scan_da_05e073_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_anonymous_ticket_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow public/anonymous ticket submissions'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_desktop_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Send desktop / browser alerts to staff'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_email_to_ticket_enabled',
            field=models.BooleanField(default=False, help_text='Convert inbound emails to tickets'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_external_alert_ingest_enabled',
            field=models.BooleanField(default=False, help_text='Accept alerts from external monitoring/RMM webhooks'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_portal_enabled',
            field=models.BooleanField(default=False, help_text='Allow customer portal access for PSA clients'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send SMS to staff (no secrets in body)'),
        ),
    ]
