# Generated by Django 6.0.4 on 2026-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional markup % applied to time entries logged by techs from this partner org when billed back to the originating client. 0 = no markup.', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_outsourcing_partner',
            field=models.BooleanField(default=False, help_text='When true, this org can receive outsourced tickets via the share-ticket-to-partner endpoint. Requires partner_secret.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='partner_endpoint_url',
            field=models.URLField(blank=True, help_text='Inbound webhook URL on the partner side that should receive ticket-share notifications.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='partner_secret',
            field=models.CharField(blank=True, help_text='HMAC shared secret for verifying inbound webhook payloads. Auto-generated when is_outsourcing_partner flips to True.', max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('fully_managed', 'Fully Managed'), ('break_fix', 'Break/Fix'), ('co_managed', 'Co-Managed'), ('consulting', 'Consulting Only'), ('project_based', 'Project-Based'), ('internal', 'Internal / Staff'), ('subcontractor', 'Subcontractor / Outsourcing Partner'), ('other', 'Other')], default='', help_text='Client service type', max_length=50),
        ),
    ]
