# Generated by Django 6.0.4 on 2026-05-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_csat_enabled',
            field=models.BooleanField(default=False, help_text='Email a 1-5 star CSAT survey link to the requester when a ticket is resolved/closed. Off by default — enable after vetting your post-close email content.'),
        ),
    ]
