# Generated by Django 6.0.4 on 2026-05-02 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_organization_portal_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent organization. Use for branch / division / subsidiary structures. The parent's queries see descendants' rows; descendants stay scoped to themselves.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.organization'),
        ),
    ]
