# Generated by Django 6.0.4 on 2026-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_organization_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_portal_announcements_enabled',
            field=models.BooleanField(default=False, help_text='Render portal announcements on the customer portal home and expose the dismiss endpoint.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_portal_customer_approvals_enabled',
            field=models.BooleanField(default=False, help_text='Show pending PSAApproval rows flagged is_client_approval to portal users + accept their decisions.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_portal_escalation_enabled',
            field=models.BooleanField(default=False, help_text='Let portal users escalate one of their tickets directly (stamps escalated_at/by/reason + posts a public comment).'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='psa_portal_voting_enabled',
            field=models.BooleanField(default=False, help_text='Let portal users "I\'m affected too" vote on tickets they can see.'),
        ),
    ]
