# Generated by Django 6.0.4 on 2026-05-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_systemsetting_late_fee_min_days_overdue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='psa_auto_push_recurring_invoices',
            field=models.BooleanField(default=False, help_text="When True, the recurring-invoice cron also pushes each newly-generated draft Invoice to the org's configured sync-enabled AccountingConnection. Off by default."),
        ),
    ]
