# Generated by Django 6.0.4 on 2026-05-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='exposure_score',
            field=models.PositiveIntegerField(default=0, help_text='Cached rolling security exposure score (0–1000). Recomputed by `manage.py recompute_exposure_scores`. Severity-weighted sum of open SecurityAlerts + open Vulnerabilities, scaled by asset count.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='exposure_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
