# Generated by Django 6.0.4 on 2026-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpsasettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable PSA for this client. Inherits the global PSA flag — use this to opt a specific client OUT.'),
        ),
    ]
