# Generated by Django 6.0.4 on 2026-04-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0002_client_settings_default_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closure_category',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('workaround', 'Workaround Provided'), ('duplicate', 'Duplicate'), ('cant_reproduce', "Can't Reproduce"), ('no_action', 'No Action Required'), ('cancelled', 'Cancelled by Requester'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Required when closing — what was the fix?'),
        ),
    ]
