# Generated by Django 6.0.4 on 2026-04-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_psa_global_surface_flags'),
        ('psa', '0003_closure_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in the dropdown', max_length=120)),
                ('body', models.TextField(help_text='Use {{ticket.number}}, {{ticket.subject}}, {{ticket.client}}, {{user.first_name}}, {{user.last_name}}, {{user.username}}')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_canned_replies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave blank for a global reply (every client).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psa_canned_replies', to='core.organization')),
            ],
            options={
                'db_table': 'psa_canned_replies',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='psa_canned__organiz_eaba84_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='psa.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_watching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_ticket_watchers',
                'indexes': [models.Index(fields=['ticket'], name='psa_ticket__ticket__66c7c8_idx'), models.Index(fields=['user'], name='psa_ticket__user_id_86b774_idx')],
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
