# Generated by Django 6.0.4 on 2026-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0005_time_and_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalogitem',
            name='fields_json',
            field=models.JSONField(blank=True, default=list, help_text='List of {key, label, type, required, placeholder, options, help} objects describing the structured fields the requester fills in. Field values substitute into default_subject + default_body via {{key}} placeholders. Supported types: text, email, date, number, textarea, select, checkbox.'),
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
