# Generated by Django 6.0.4 on 2026-04-28 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('psa', '0008_alter_ticket_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIngestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('use_ssl', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField(blank=True)),
                ('folder', models.CharField(default='INBOX', max_length=100)),
                ('subject_ticket_pattern', models.CharField(default='PSA-\\d{4}-\\d{6}', help_text='Regex; first match in the subject is treated as a reply to that ticket', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_configs', to='psa.ticketpriority')),
                ('default_queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_configs', to='psa.queue')),
                ('default_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_configs', to='psa.tickettype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ingestion_configs', to='core.organization')),
            ],
            options={
                'db_table': 'psa_email_ingestion_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('block_hours', 'Block of Hours'), ('retainer', 'Monthly Retainer'), ('managed_services', 'Managed Services'), ('per_incident', 'Per-Incident')], default='block_hours', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Open-ended if blank', null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Allowance for block_hours / retainer; 0 for unlimited', max_digits=10)),
                ('hours_used_minutes', models.PositiveIntegerField(default=0, help_text='Auto-incremented by TicketTimeEntry; minutes for precision')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Effective rate when consuming or overaging', max_digits=10)),
                ('overage_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate for hours beyond total_hours (defaults to hourly_rate when 0)', max_digits=10)),
                ('sla_matrix', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(help_text='Client the contract is with', on_delete=django.db.models.deletion.CASCADE, related_name='psa_client_contracts', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_psa_contracts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the contract', on_delete=django.db.models.deletion.CASCADE, related_name='psa_msp_contracts', to='core.organization')),
            ],
            options={
                'db_table': 'psa_contracts',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['organization', 'client_org', 'status'], name='psa_contrac_organiz_e894ec_idx')],
            },
        ),
    ]
