# Generated by Django 6.0.4 on 2026-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0009_emailingestionconfig_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='source',
            field=models.CharField(default='manual', help_text='manual | email | portal | api', max_length=20),
        ),
    ]
