# Generated by Django 6.0.4 on 2026-04-28 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0014_invoice_invoicelineitem_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer_token',
            field=models.CharField(blank=True, db_index=True, help_text='Opaque token for the customer-facing sign-and-accept URL', max_length=64),
        ),
        migrations.CreateModel(
            name='QuoteSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_name', models.CharField(max_length=200)),
                ('signed_by_email', models.EmailField(max_length=254)),
                ('signed_by_title', models.CharField(blank=True, help_text="Optional — signer's job title", max_length=200)),
                ('signature_data', models.TextField(help_text='Base64 data URI of the drawn signature (image/png)')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='psa.quote')),
            ],
            options={
                'db_table': 'psa_quote_signatures',
            },
        ),
    ]
