# Generated by Django 6.0.4 on 2026-04-28 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
        ('psa', '0015_quote_customer_token_quotesignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive value. Use is_credit to subtract from balance.', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('charge_date', models.DateField()),
                ('is_credit', models.BooleanField(default=False, help_text="Credit/refund — subtracts from the client's outstanding balance")),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('once', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20)),
                ('next_run_at', models.DateField(blank=True, help_text='When the next recurring instance should be created (for is_recurring=True)', null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_client_charges', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_psa_charges', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_consumed', to='psa.invoice')),
                ('organization', models.ForeignKey(help_text='MSP tenant', on_delete=django.db.models.deletion.CASCADE, related_name='psa_charges', to='core.organization')),
            ],
            options={
                'db_table': 'psa_charges',
                'ordering': ['-charge_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'client_org', '-charge_date'], name='psa_charges_organiz_085acf_idx'), models.Index(fields=['client_org', 'invoiced'], name='psa_charges_client__8abf15_idx'), models.Index(fields=['is_recurring', 'next_run_at'], name='psa_charges_is_recu_1059b6_idx')],
            },
        ),
    ]
