# Generated by Django 6.0.4 on 2026-04-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0017_alter_workflowrule_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='When true, the renewal cron auto-creates the next period on end_date and applies rollover/proration.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renew_period_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Length of each auto-renewed period in months.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='billable_role_codes',
            field=models.JSONField(blank=True, default=list, help_text="List of role codes whose time entries count against this contract's allowance. Empty list = all roles count."),
        ),
        migrations.AddField(
            model_name='contract',
            name='excluded_role_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of role codes whose time entries bypass this contract (e.g. project work). Wins over billable_role_codes.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='parent_contract',
            field=models.ForeignKey(blank=True, help_text='Previous-period contract this one rolled forward from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='psa.contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proration_enabled',
            field=models.BooleanField(default=False, help_text='When true, mid-month start/cancel prorates the allowance based on days active in the period.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rolled_over_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes carried over from the prior period (auto-set by the renewal cron). Consumed before total_hours.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rollover_expires_at',
            field=models.DateField(blank=True, help_text='Date when carried-over minutes expire (set by renewal cron from rollover_expiry_days).', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='rollover_expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after the new period start that rolled-over hours expire. 0 = never expire.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rollover_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% of unused hours that roll into the next period when this contract auto-renews (0–100). 0 = no rollover.', max_digits=5),
        ),
        migrations.CreateModel(
            name='ContractBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_label', models.CharField(blank=True, help_text='e.g. "seat", "device", "mailbox" — display only.', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recurring_period', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='psa.contract')),
            ],
            options={
                'db_table': 'psa_contract_bundle_items',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
