# Generated by Django 6.0.4 on 2026-04-29 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
        ('psa', '0018_contract_auto_renew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30, unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_phone', models.CharField(blank=True, max_length=40)),
                ('vendor_address', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to vendor'), ('acknowledged', 'Vendor acknowledged'), ('partial', 'Partially received'), ('received', 'Fully received'), ('cancelled', 'Cancelled'), ('void', 'Void')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('is_drop_ship', models.BooleanField(default=False, help_text='If true, ship-to overrides MSP address with client address.')),
                ('ship_to_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_po_client', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_po_msp', to='core.organization')),
            ],
            options={
                'db_table': 'psa_purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('distributor_provider', models.CharField(blank=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Phase 4.2 fills this from Receiving.', max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='psa.purchaseorder')),
            ],
            options={
                'db_table': 'psa_purchase_order_lines',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to PO'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client_org', models.ForeignKey(blank=True, help_text='Optional - bill to / drop-ship to this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_pr_client', to='core.organization')),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the requisition.', on_delete=django.db.models.deletion.CASCADE, related_name='psa_pr_msp', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='psa.project')),
                ('source_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_purchase_requisitions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='psa.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, help_text='Vendor SKU or part number - pre-fills from distributor catalog.', max_length=80)),
                ('distributor_provider', models.CharField(blank=True, help_text='Hint: which distributor (ingram/pax8/synnex) carries this SKU.', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='psa.purchaserequisition')),
            ],
            options={
                'db_table': 'psa_purchase_requisition_lines',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'status', '-requested_at'], name='psa_purchas_organiz_73a22a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['client_org'], name='psa_purchas_client__5bc6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='psa_purchas_organiz_f5fdf4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor_name'], name='psa_purchas_vendor__5190b2_idx'),
        ),
    ]
