# Generated by Django 6.0.4 on 2026-04-29 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0019_purchaseorder_purchaseorderlineitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POBackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_orders', to='psa.purchaseorder')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_orders', to='psa.purchaseorderlineitem')),
            ],
            options={
                'db_table': 'psa_po_back_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.CharField(blank=True, max_length=80)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_drop_ship_confirmed', models.BooleanField(default=False, help_text='When the PO is drop-ship and the client confirmed delivery.')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='psa.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_po_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='POReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_numbers', models.JSONField(blank=True, default=list, help_text='List of serial numbers captured at receive time. Auto-create assets.Asset rows when set.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='psa.purchaseorderlineitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='psa.poreceipt')),
            ],
            options={
                'db_table': 'psa_po_receipt_lines',
            },
        ),
    ]
