# Generated by Django 6.0.4 on 2026-04-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_vendor_account_number_vendor_billing_address_and_more'),
        ('psa', '0020_pobackorder_poreceipt_poreceiptline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Link to assets.Vendor for procurement metadata; snapshot fields below are auto-filled at save time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='assets.vendor'),
        ),
    ]
