# Generated by Django 6.0.4 on 2026-04-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('psa', '0025_servicecatalogitem_last_published_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted by Partner'), ('declined', 'Declined by Partner'), ('completed', 'Work Completed'), ('recalled', 'Recalled by Originator')], default='pending', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional context passed to the partner.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('partner_org', models.ForeignKey(limit_choices_to={'is_outsourcing_partner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_shared_tickets', to='core.organization')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_shares',
                'ordering': ['-shared_at'],
                'unique_together': {('ticket', 'partner_org')},
            },
        ),
    ]
