# Generated by Django 6.0.4 on 2026-05-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('psa', '0028_email_routing_and_quarantine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approval_reason',
            field=models.CharField(blank=True, help_text='Why the invoice was flagged — surfaced to the approver.', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_psa_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Set when the invoice exceeds a pre-billing approval threshold (total or contract overage %). Must be approved before status can move from draft → sent.'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['requires_approval', 'approved_at'], name='psa_invoice_require_d5f6f7_idx'),
        ),
    ]
