# Generated by Django 6.0.4 on 2026-05-02 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_systemsetting_psa_csat_enabled'),
        ('psa', '0029_invoice_approval_reason_invoice_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCSATSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 = very dissatisfied, 5 = very satisfied. Null until response.', null=True)),
                ('comment', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_csat_surveys', to='core.organization')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat_survey', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_ticket_csat_surveys',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['organization', '-sent_at'], name='psa_ticket__organiz_d95246_idx'), models.Index(fields=['rating'], name='psa_ticket__rating_014875_idx')],
            },
        ),
    ]
