# Generated by Django 6.0.4 on 2026-05-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0032_ticket_escalated_at_ticket_escalated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='psa.ticketcomment'),
        ),
    ]
