# Generated by Django 6.0.4 on 2026-05-02 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_organization_portal_primary_color'),
        ('psa', '0033_ticketcomment_parent_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psaapproval',
            name='is_client_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='psaapproval',
            index=models.Index(fields=['is_client_approval', 'status'], name='psa_approva_is_clie_4aa9ea_idx'),
        ),
    ]
