# Generated by Django 6.0.4 on 2026-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0035_timesheetsubmission_tickettimeentry_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psaapproval',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text="When the escalation digest mentioned this approval. Set by `psa_escalate_idle_approvals` so an approval isn't escalated repeatedly.", null=True),
        ),
        migrations.AddField(
            model_name='psaapproval',
            name='escalation_threshold_hours',
            field=models.PositiveIntegerField(default=48, help_text='Approvals still pending after this many hours get flagged in the daily escalation digest. 0 = never escalate.'),
        ),
    ]
