# Generated by Django 6.0.4 on 2026-05-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0036_psaapproval_escalated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credits_invoice',
            field=models.ForeignKey(blank=True, help_text='When set, this credit memo was issued against the named source invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_memos', to='psa.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credit_memo',
            field=models.BooleanField(default=False, help_text='True for credit memos (negative-amount invoices).'),
        ),
    ]
