# Generated by Django 6.0.4 on 2026-05-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0037_invoice_credits_invoice_invoice_is_credit_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psaapproval',
            name='parent_approval',
            field=models.ForeignKey(blank=True, help_text='When set, this approval is a stage in a chain — it cannot leave `blocked` until the parent is approved.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_stages', to='psa.psaapproval'),
        ),
        migrations.AddField(
            model_name='psaapproval',
            name='stage_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 for stand-alone approvals; 1+ for chain stages (stage 1 starts as "pending", later stages start "blocked").'),
        ),
        migrations.AlterField(
            model_name='psaapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked (waiting on prior stage)')], default='pending', max_length=20),
        ),
    ]
