# Generated by Django 6.0.4 on 2026-05-05 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_accountingauditlog'),
        ('psa', '0043_invoicelineitem_gl_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='target_connection',
            field=models.ForeignKey(blank=True, help_text='Pin the invoice to a specific accounting connection — required for orgs with multiple QBO/Xero books.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_invoices', to='integrations.accountingconnection'),
        ),
    ]
