# Generated by Django 6.0.4 on 2026-05-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0045_payment_bank_deposit_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrule',
            name='else_actions',
            field=models.JSONField(blank=True, default=list, help_text='Actions to run when conditions evaluate false. Empty = no-op when conditions fail.'),
        ),
    ]
