# Generated by Django 6.0.4 on 2026-05-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0047_workflowrule_fire_once_per_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRuleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('routing', 'Routing'), ('sla', 'SLA / escalation'), ('notification', 'Notification'), ('cleanup', 'Cleanup / housekeeping'), ('other', 'Other')], default='other', max_length=30)),
                ('trigger', models.CharField(choices=[('ticket_created', 'Ticket created'), ('ticket_updated', 'Ticket updated'), ('status_changed', 'Status changed'), ('comment_added', 'Comment added'), ('sla_threshold_crossed', 'SLA threshold crossed')], max_length=30)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('else_actions', models.JSONField(blank=True, default=list)),
                ('fire_once_per_ticket', models.BooleanField(default=False)),
                ('is_built_in', models.BooleanField(default=False, help_text="Built-in templates ship with the project; user-created ones are False. Built-ins can't be deleted via the UI.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psa_workflow_rule_templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
