# Generated by Django 6.0.4 on 2026-05-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_organization_region_organization_sla_overrides'),
        ('psa', '0048_workflowruletemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='Plain-text reason — "12 P1 tickets in 30d auto-routed to Bob → consider a skill-match rule"', max_length=400)),
                ('rationale', models.TextField(blank=True, help_text='Optional longer explanation; future LLM suggesters can put their reasoning here.')),
                ('suggested_payload', models.JSONField(blank=True, default=dict, help_text='Draft WorkflowRule payload — name, trigger, conditions, actions, etc. Used by accept().')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_rule', models.ForeignKey(blank=True, help_text='Set on accept() to point at the materialized rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='psa.workflowrule')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Optional client scope. None = MSP-wide suggestion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psa_workflow_suggestions', to='core.organization')),
            ],
            options={
                'db_table': 'psa_workflow_suggestions',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['status', '-generated_at'], name='psa_workflo_status_a42100_idx')],
            },
        ),
    ]
