# Generated by Django 6.0.4 on 2026-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa', '0051_contractmeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='When True, the lifecycle cron transitions the contract to `cancelled` after the next billing date.'),
        ),
        migrations.AddField(
            model_name='contract',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When the contract was paused. Non-null = paused.', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='paused_until',
            field=models.DateField(blank=True, help_text='Optional auto-resume date — `psa_advance_subscription_lifecycle` cron clears the pause when today >= this date.', null=True),
        ),
    ]
