# Generated by Django 6.0.4 on 2026-05-05 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        ('psa', '0052_contract_cancel_at_period_end_contract_paused_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('miles', models.DecimalField(decimal_places=2, help_text='Distance in miles', max_digits=8)),
                ('is_auto', models.BooleanField(default=False, help_text='True when computed from geofences; False when entered manually.')),
                ('start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('purpose', models.CharField(blank=True, help_text='Optional label, e.g. "Onsite at ACME / Boston site"', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_mileage_logs', to='core.organization')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_mileage_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_logs', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_mileage_logs',
                'ordering': ['-trip_date', '-created_at'],
                'indexes': [models.Index(fields=['technician', '-trip_date'], name='psa_mileage_technic_3af56c_idx'), models.Index(fields=['organization', '-trip_date'], name='psa_mileage_organiz_a8e200_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('arrival_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('departure_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('departure_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psa_site_visits', to='core.organization')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psa_site_visits', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='psa.ticket')),
            ],
            options={
                'db_table': 'psa_site_visits',
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['ticket', '-checked_in_at'], name='psa_site_vi_ticket__3fca08_idx'), models.Index(fields=['technician', '-checked_in_at'], name='psa_site_vi_technic_c7214c_idx'), models.Index(fields=['organization', 'checked_out_at'], name='psa_site_vi_organiz_247db7_idx')],
            },
        ),
    ]
