# Generated by Django 6.0.4 on 2026-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_asset_health_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='vendor',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_lead_time_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Typical days from PO sent to delivery. Used for auto-replenish expected_delivery_date.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='distributor_provider',
            field=models.CharField(blank=True, help_text='Optional link to existing distributor integration: ingram / pax8 / synnex / etc.', max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid'), ('credit_card', 'Credit Card')], max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('portal', 'Vendor Portal')], max_length=20),
        ),
    ]
