# Generated by Django 6.0.4 on 2026-05-05 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_service'),
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Optional human label, e.g. "post-deployment v1.0".', max_length=100)),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Field map captured by `Asset.capture_baseline()`.')),
                ('is_current', models.BooleanField(default=False, help_text='True for the most-recent baseline of this asset; previous baselines are kept for history.')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='assets.asset')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_baselines', to='core.organization')),
            ],
            options={
                'db_table': 'asset_baselines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', '-created_at'], name='asset_basel_asset_i_d60a5a_idx'), models.Index(fields=['asset', 'is_current'], name='asset_basel_asset_i_ecf70f_idx')],
            },
        ),
    ]
