# Generated by Django 6.0.4 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='config_monitored',
            field=models.BooleanField(default=False, help_text='Auto-capture baselines on the daily cron when True.'),
        ),
    ]
