# Generated by Django 6.0.4 on 2026-04-29 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_accountingconnection'),
        ('processes', '0004_processexecution_psa_note_internal'),
        ('psa', '0016_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexecution',
            name='native_psa_ticket',
            field=models.ForeignKey(blank=True, help_text='Related native PSA ticket — set when a tech launches the workflow from the ticket detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_executions', to='psa.ticket'),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='psa_ticket',
            field=models.ForeignKey(blank=True, help_text='Related external (third-party) PSA ticket for this execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_executions', to='integrations.psaticket'),
        ),
    ]
