# Generated by Django 6.0.4 on 2026-05-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_processexecution_native_psa_ticket_and_more'),
        ('psa', '0028_email_routing_and_quarantine'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstagecompletion',
            name='spawned_ticket',
            field=models.ForeignKey(blank=True, help_text='PSA ticket created from this stage via the runbook-to-ticket flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_from_stage_completions', to='psa.ticket'),
        ),
        migrations.AlterField(
            model_name='process',
            name='category',
            field=models.CharField(choices=[('onboarding', 'User Onboarding'), ('offboarding', 'User Offboarding'), ('client_onboarding', 'Client Onboarding'), ('client_offboarding', 'Client Offboarding'), ('client_termination', 'Client Termination'), ('deployment', 'System Deployment'), ('maintenance', 'Maintenance'), ('incident', 'Incident Response'), ('backup', 'Backup/Recovery'), ('security', 'Security Audit'), ('change', 'Change Management'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
