# Generated by Django 6.0.4 on 2026-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_membership_is_org_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='psa_ai_request_triage',
            field=models.BooleanField(default=True, help_text='Request read-only AI triage guidance for a ticket (advisory output only)'),
        ),
    ]
