# Generated by Django 6.0.4 on 2026-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_roletemplate_billing_record_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='procurement_approve_pr',
            field=models.BooleanField(default=False, help_text='Approve / reject submitted Purchase Requisitions.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='procurement_create_po',
            field=models.BooleanField(default=False, help_text='Create / edit Purchase Orders and convert PR to PO.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='procurement_create_pr',
            field=models.BooleanField(default=True, help_text='Create / edit Purchase Requisitions (techs file these).'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='procurement_send_po',
            field=models.BooleanField(default=False, help_text='Email PO PDF to vendor and mark as sent.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='procurement_view',
            field=models.BooleanField(default=True, help_text='View Purchase Requisitions and Purchase Orders.'),
        ),
    ]
