# Generated by Django 6.0.4 on 2026-04-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_roletemplate_procurement_approve_pr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='crm_create_lead',
            field=models.BooleanField(default=False, help_text='Create / edit leads (file inbound prospects).'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='crm_manage_campaigns',
            field=models.BooleanField(default=False, help_text='Create / edit marketing campaigns and view ROI.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='crm_manage_pipeline',
            field=models.BooleanField(default=False, help_text='Move opportunities through stages, convert leads, create / edit opportunities.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='crm_view',
            field=models.BooleanField(default=False, help_text='View leads, opportunities, campaigns, and the pipeline.'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='crm_view_forecast',
            field=models.BooleanField(default=False, help_text='See $-weighted pipeline forecast (revenue projections).'),
        ),
    ]
