# Generated by Django 6.0.4 on 2026-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_roletemplate_problem_assign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='vault_manage_access_rules',
            field=models.BooleanField(default=False, help_text='Create / edit / delete vault GeoIP / IP / time access rules.'),
        ),
    ]
