# Generated by Django 6.0.4 on 2026-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_roletemplate_catalog_approve_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletemplate',
            name='outsourcing_share_tickets',
            field=models.BooleanField(default=False, help_text='Share a ticket with an outsourcing partner via HMAC-signed webhook.'),
        ),
    ]
