# Generated by Django 6.0.4 on 2026-05-07 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('field_ops', '0002_timeclockentry_mobiledevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=90)),
                ('apply_to_geofence_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_retention_policy', to='core.organization')),
            ],
            options={
                'verbose_name': 'Location retention policy',
                'verbose_name_plural': 'Location retention policies',
            },
        ),
    ]
