# Generated by Django 6.0.4 on 2026-05-07 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_organization_exposure_score_and_more'),
        ('field_ops', '0003_locationretentionpolicy'),
        ('psa', '0056_ticketcomment_voice_meta_tickettimeentry_end_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTimePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('always_on', 'Always on (auto-start time entries silently)'), ('ask_first', 'Ask first (push notification, requires confirm)'), ('off', 'Off (no auto-time)')], default='ask_first', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_time_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto-time preference',
                'verbose_name_plural': 'Auto-time preferences',
            },
        ),
        migrations.CreateModel(
            name='PendingAutoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='field_ops.clientsitegeofence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.organization')),
                ('suggested_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='psa.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_auto_time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['user', '-entered_at'], name='field_ops_p_user_id_6f31b7_idx')],
            },
        ),
    ]
