# Generated by Django 6.0.4 on 2026-05-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_document_is_featured_in_portal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Pending approval — hidden from the regular KB list and the customer portal until an approver publishes.'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the owner last marked this article reviewed. Drives the review reminder cron.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for keeping this article current. Receives review reminders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the article was first published.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='When true, edits move the article into a draft state until an approver publishes it.'),
        ),
        migrations.AddField(
            model_name='document',
            name='review_interval_days',
            field=models.PositiveIntegerField(default=90, help_text='Send a review reminder this many days after the last review. 0 = never remind.'),
        ),
    ]
