# Generated by Django 6.0.4 on 2026-04-29 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Microsoft 365 Certified: Modern Desktop Administrator"', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='e.g. Microsoft, Cisco, CompTIA, AWS', max_length=120)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='Leave blank if no expiry.', null=True)),
                ('verification_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='PDF or image of the certificate.', null=True, upload_to='certifications/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_user_certifications',
                'ordering': ['-issued_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_working_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_working_hours',
                'ordering': ['user', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_user_skills',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
