# Generated by Django 6.0.4 on 2026-04-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
        ('resourcing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillableTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours_per_week', models.DecimalField(decimal_places=2, default=32, help_text='Hours per week the tech should bill against client work.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_billable_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_billable_targets',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('is_recurring_yearly', models.BooleanField(default=False, help_text='If true, the date applies every year (only month + day matter).')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL = applies to every org (e.g. national holidays).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_holidays', to='core.organization')),
            ],
            options={
                'db_table': 'resourcing_holidays',
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['organization', 'date'], name='resourcing__organiz_fd3524_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Day'), ('bereavement', 'Bereavement'), ('jury_duty', 'Jury Duty'), ('parental', 'Parental Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], default='vacation', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False, help_text='Half-day flag — only meaningful when start_date == end_date.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcing_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resourcing_leave_requests',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='resourcing__user_id_47402c_idx'), models.Index(fields=['start_date', 'end_date'], name='resourcing__start_d_6675fb_idx')],
            },
        ),
    ]
