# Generated by Django 6.0.4 on 2026-04-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_vendor_account_number_vendor_billing_address_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_replenished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to suggest in auto-replenish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_inventory_items', to='assets.vendor'),
        ),
    ]
