# Generated by Django 6.0.4 on 2026-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='output_format',
            field=models.CharField(default='pdf', help_text='Output format: pdf | csv | excel | json', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
