# Generated by Django 6.0.4 on 2026-05-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_organization_billing_markup_pct_and_more'),
        ('reports', '0003_wallboards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallboard',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Org that owns this wallboard. Leave empty for a "Global" board visible to staff/superusers and aggregating across every tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallboards', to='core.organization'),
        ),
    ]
