# Generated by Django 6.0.4 on 2026-05-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_systemsetting_psa_portal_announcements_enabled_and_more'),
        ('reports', '0004_alter_wallboard_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(choices=[('psa.Ticket', 'PSA Tickets'), ('assets.Asset', 'Assets'), ('vault.Password', 'Vault Passwords')], help_text='Which app+model to query.', max_length=80)),
                ('filters', models.JSONField(blank=True, default=list, help_text='List of {field, op, value} dicts. Bad fields are silently ignored at run time.')),
                ('columns', models.JSONField(blank=True, default=list, help_text="Ordered list of field names to render. Empty = all columns from the target_model's default set.")),
                ('sort_by', models.CharField(blank=True, max_length=120)),
                ('is_shared', models.BooleanField(default=False, help_text='When true, other members of the same organization can see + run this query.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_count', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, help_text='Optional. When set, results are filtered to this org. Null = run against every org the requester can see.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_saved_queries',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', '-updated_at'], name='reports_sav_owner_i_a05031_idx'), models.Index(fields=['organization', 'is_shared'], name='reports_sav_organiz_3f9f72_idx')],
            },
        ),
    ]
