# Generated by Django 6.0.4 on 2026-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psa_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestion',
            name='kind',
            field=models.CharField(choices=[('reply', 'Reply'), ('action', 'Action'), ('triage', 'Triage Guidance')], max_length=20),
        ),
    ]
