# Generated by Django 6.0.4 on 2026-04-30 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_systemsetting_psa_default_currency_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 auto-computed by the lead scoring service. Higher = hotter.'),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority (matches first).')),
                ('min_value', models.DecimalField(decimal_places=2, default=0, help_text='Only opportunities with estimated_value >= this. 0 = no floor.', max_digits=12)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=0, help_text='Commission as a % of opportunity estimated_value.', max_digits=5)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed bonus on top of % (or instead, when rate_pct=0).', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_user', models.ForeignKey(blank=True, help_text='Restrict to a specific tech/sales user. Blank = applies to anyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_commission_rules', to='core.organization')),
            ],
            options={
                'db_table': 'crm_commission_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_reference', models.CharField(blank=True, help_text='Payroll reference / batch ID.', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='crm.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_commissions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, help_text='Which rule produced this commission (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='crm.commissionrule')),
            ],
            options={
                'db_table': 'crm_commissions',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['organization', 'is_active', 'priority'], name='crm_commiss_organiz_18b874_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['user', 'status'], name='crm_commiss_user_id_d5eaef_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['opportunity'], name='crm_commiss_opportu_961196_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('opportunity', 'user')},
        ),
    ]
