# Generated by Django 6.0.4 on 2026-04-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('integrations', '0021_fix_unifi_mode_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('ingram_xvantage', 'Ingram Micro Xvantage'), ('synnex', 'TD Synnex'), ('d_and_h', 'D&H Distributing'), ('scansource', 'ScanSource'), ('pax8', 'Pax8'), ('qbs', 'QBS Software'), ('westcoast', 'Westcoast')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, help_text="Optional — defaults to the provider's production endpoint", max_length=500)),
                ('encrypted_credentials', models.TextField(blank=True, help_text='Encrypted JSON with API keys, customer IDs, etc.')),
                ('encrypted_webhook_secret', models.TextField(blank=True)),
                ('webhook_token', models.CharField(blank=True, db_index=True, help_text='Random token in the webhook URL — first defence-in-depth check before signature validation', max_length=64)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('sync_catalog', models.BooleanField(default=False, help_text='Sync the full product catalog (large; opt-in)')),
                ('sync_pricing', models.BooleanField(default=True, help_text='Pull pricing on-demand for SKUs in tickets')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=1440, help_text='How often the catalog sync runs (default daily)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_connections', to='core.organization')),
            ],
            options={
                'db_table': 'distributor_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DistributorWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('body_truncated', models.TextField(blank=True)),
                ('headers_summary', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('process_error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.distributorconnection')),
            ],
            options={
                'db_table': 'distributor_webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['connection', '-received_at'], name='distributor_connect_87b515_idx')],
            },
        ),
    ]
