# Generated by Django 6.0.4 on 2026-04-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_fix_psa_ai_fields'),
        ('integrations', '0022_distributor_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('quickbooks_online', 'QuickBooks Online'), ('xero', 'Xero'), ('freshbooks', 'FreshBooks'), ('wave', 'Wave Accounting'), ('zoho_books', 'Zoho Books'), ('sage_business_cloud', 'Sage Business Cloud')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='Defaults to provider production endpoint when blank', max_length=500)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Allow live invoice push (off by default — sandbox first)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_connections', to='core.organization')),
            ],
            options={
                'db_table': 'accounting_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
