# Generated by Django 6.0.4 on 2026-05-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_systemsetting_invoice_approval_overage_pct_and_more'),
        ('integrations', '0023_accountingconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('push_invoice', 'Push Invoice'), ('record_payment', 'Record Payment'), ('test_connection', 'Test Connection'), ('refresh_token', 'Refresh Token')], max_length=40)),
                ('resource_type', models.CharField(blank=True, help_text='e.g. invoice, payment', max_length=40)),
                ('resource_id', models.CharField(blank=True, help_text='Local PK of the source row (Invoice.pk / Payment.pk)', max_length=120)),
                ('external_id', models.CharField(blank=True, help_text='Provider-side ID returned on success', max_length=120)),
                ('success', models.BooleanField(default=False)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('request_summary', models.CharField(blank=True, max_length=500)),
                ('response_summary', models.CharField(blank=True, max_length=500)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='integrations.accountingconnection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_audit_logs', to='core.organization')),
            ],
            options={
                'db_table': 'accounting_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='accounting__organiz_2bdae8_idx'), models.Index(fields=['connection', '-created_at'], name='accounting__connect_336c28_idx'), models.Index(fields=['action', 'success'], name='accounting__action_8ef67c_idx')],
            },
        ),
    ]
