# Generated by Django 6.0.4 on 2026-05-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_systemsetting_late_fee_min_days_overdue_and_more'),
        ('integrations', '0024_accountingauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('stripe', 'Stripe (cards + ACH)'), ('gocardless', 'GoCardless (Direct Debit / ACH)'), ('manual', 'Manual / external (no automation)')], default='manual', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Allow live charges (off by default — sandbox first).')),
                ('last_charge_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_connections', to='core.organization')),
            ],
            options={
                'db_table': 'payment_connections',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
