# Generated by Django 6.0.4 on 2026-04-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_vendor_account_number_vendor_billing_address_and_more'),
        ('vehicles', '0007_receipt_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinventoryitem',
            name='last_replenished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopinventoryitem',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to suggest in auto-replenish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_shop_inventory_items', to='assets.vendor'),
        ),
        migrations.AddField(
            model_name='vehicleinventoryitem',
            name='last_replenished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinventoryitem',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor to suggest in auto-replenish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_vehicle_inventory_items', to='assets.vendor'),
        ),
        migrations.AlterField(
            model_name='vehiclereceipt',
            name='description',
            field=models.TextField(blank=True, help_text='Line items or description from receipt'),
        ),
        migrations.AlterField(
            model_name='vehiclereceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehiclereceipt',
            name='odometer',
            field=models.IntegerField(blank=True, help_text='Odometer / mileage reading shown on receipt (optional)', null=True),
        ),
    ]
