# Generated by Django 6.0.4 on 2026-04-30 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_systemsetting_crm_enabled'),
        ('vault', '0011_password_client_access_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = checked first.')),
                ('effect', models.CharField(choices=[('allow', 'Allow access'), ('deny', 'Deny access')], default='allow', max_length=20)),
                ('scope', models.CharField(choices=[('item', 'Specific Password'), ('user', 'Specific User'), ('organization', 'Organization')], max_length=20)),
                ('allowed_countries', models.JSONField(blank=True, default=list, help_text='ISO codes that pass. Empty = no country restriction. Example: ["US", "CA", "GB"].')),
                ('blocked_countries', models.JSONField(blank=True, default=list, help_text='ISO codes that fail (overrides allowed_countries).')),
                ('allowed_cidrs', models.JSONField(blank=True, default=list, help_text='Source IP CIDRs that pass. Empty = no IP restriction. Example: ["10.0.0.0/8", "203.0.113.0/24"].')),
                ('blocked_cidrs', models.JSONField(blank=True, default=list, help_text='Source IP CIDRs that fail (overrides allowed_cidrs).')),
                ('allowed_weekdays', models.JSONField(blank=True, default=list, help_text='List of weekday integers 0=Monday .. 6=Sunday. Empty = all days allowed.')),
                ('allowed_hour_start', models.TimeField(blank=True, help_text='Earliest hour (in `timezone`) that access is allowed. Blank = no time floor.', null=True)),
                ('allowed_hour_end', models.TimeField(blank=True, help_text='Latest hour. Blank = no time ceiling.', null=True)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone name for the time window.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant that owns the rule. For organization-scoped rules this is also the target.', on_delete=django.db.models.deletion.CASCADE, related_name='vault_access_rules', to='core.organization')),
                ('target_password', models.ForeignKey(blank=True, help_text='Required when scope=item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='vault.password')),
                ('target_user', models.ForeignKey(blank=True, help_text='Required when scope=user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_access_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_access_rules',
                'ordering': ['priority', '-updated_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='vault_acces_organiz_8aedeb_idx'), models.Index(fields=['scope', 'is_active'], name='vault_acces_scope_94bcec_idx')],
            },
        ),
    ]
