# Generated by Django 6.0.4 on 2026-05-02 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_vaultaccessrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='requires_reveal_approval',
            field=models.BooleanField(default=False, help_text="When set, revealing this password requires an approved VaultRevealRequest (or an explicit break-glass override) rather than just the requester's permissions."),
        ),
        migrations.CreateModel(
            name='VaultRevealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(help_text='Why the requester needs to reveal this password.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('is_break_glass', models.BooleanField(default=False, help_text='True when the requester self-approved via the emergency break-glass flow. Logs harder + auto-notifies admins.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the approved reveal window closes. Default: 1 hour after approval. Reveals after this point require a fresh request.', null=True)),
                ('revealed_at', models.DateTimeField(blank=True, help_text='When the requester actually revealed the password using this approval. Single-use (cleared on use).', null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_reveal_decisions', to=settings.AUTH_USER_MODEL)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveal_requests', to='vault.password')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_reveal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_reveal_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['password', 'status'], name='vault_revea_passwor_03f031_idx'), models.Index(fields=['requester', '-requested_at'], name='vault_revea_request_cd3a2c_idx'), models.Index(fields=['status', 'expires_at'], name='vault_revea_status_161ae1_idx')],
            },
        ),
    ]
