# Generated by Django 6.0.4 on 2026-05-05 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        ('vault', '0013_password_requires_reveal_approval_vaultrevealrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebExtensionAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Opaque bearer secret returned to the extension at issue.', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='User-friendly label (e.g. "Chrome on Mac").', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Hard expiry. Tokens past this point cannot authenticate.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Optional organization pin. NULL = token honours the X-Organization-Id header per request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_tokens', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_webextension_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='vault_webex_user_id_e43a76_idx'), models.Index(fields=['expires_at'], name='vault_webex_expires_b907a7_idx')],
            },
        ),
    ]
