# Generated by Django 6.0.4 on 2026-05-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_systemsetting_psa_auto_push_recurring_invoices'),
        ('psa', '0056_ticketcomment_voice_meta_tickettimeentry_end_lat_and_more'),
        ('security_alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalert',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Source vendor connection (poller / vendor webhook). Null when the alert was ingested via a SIEM endpoint.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security_alerts.securityvendorconnection'),
        ),
        migrations.CreateModel(
            name='SIEMWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('expected_format', models.CharField(choices=[('cef', 'CEF (Common Event Format)'), ('json', 'Generic JSON'), ('syslog', 'Syslog (RFC 5424)')], default='cef', max_length=20)),
                ('token', models.CharField(help_text='Per-endpoint token used in the URL path. Auto-generated.', max_length=64, unique=True)),
                ('hmac_secret', models.CharField(blank=True, help_text='If set, inbound POSTs MUST send an X-Cst0r-Signature header containing hex-encoded HMAC-SHA256(secret, body).', max_length=64)),
                ('require_hmac', models.BooleanField(default=False, help_text='When True, requests without a valid signature are rejected with HTTP 403. When False, signature is verified IF sent but optional.')),
                ('default_severity', models.CharField(choices=[('info', 'Informational'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity used when the inbound payload omits one.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('received_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(blank=True, help_text='Optionally pin the endpoint to a specific client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siem_webhook_endpoints_for_client', to='core.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='MSP tenant that owns the endpoint.', on_delete=django.db.models.deletion.CASCADE, related_name='siem_webhook_endpoints', to='core.organization')),
            ],
            options={
                'db_table': 'siem_webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='securityalert',
            unique_together={('connection', 'external_id')},
        ),
        migrations.AddField(
            model_name='securityalert',
            name='siem_endpoint',
            field=models.ForeignKey(blank=True, help_text='Phase 23 v3.17.337: source SIEM webhook endpoint when the alert came in via /security/siem/webhook/.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='security_alerts.siemwebhookendpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='securityalert',
            unique_together={('connection', 'external_id'), ('siem_endpoint', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['siem_endpoint', '-seen_at'], name='security_al_siem_en_0bd474_idx'),
        ),
        migrations.AddIndex(
            model_name='siemwebhookendpoint',
            index=models.Index(fields=['organization', 'is_active'], name='siem_webhoo_organiz_1e0669_idx'),
        ),
        migrations.AddIndex(
            model_name='siemwebhookendpoint',
            index=models.Index(fields=['token'], name='siem_webhoo_token_d32869_idx'),
        ),
    ]
